### ISSUE TITLE
nelson submit() cannot be used as an imported module in other scripts

### ISSUE THREAD

**Issue by cgearhart** [udacity/nelson#3]
Using [`sys.argv[0]`](https://github.com/udacity/nelson/blob/master/nelson/abstract.py#L93) as the root path for the zip file means that other executable scripts cannot call the submit function. For example: https://github.gatech.edu/omscs6475/assignments/blob/master/submit.py#L56 will fail because sys.argv[0] when console script `cs6475` is run from /usr/local/bin is not the current working directory:

```
Traceback (most recent call last):
  File "/usr/local/bin/cs6475", line 9, in <module>
    load_entry_point('cs6475==0.1', 'console_scripts', 'cs6475')()
  File "/vagrant/fall2017/assignments/submit.py", line 114, in main
    submit(settings["course_id"], args, settings["quizzes"][args.quiz])
  File "/vagrant/fall2017/assignments/submit.py", line 59, in submit
    max_zip_size=settings.get("size", 8) << 20)
  File "build/bdist.linux-x86_64/egg/nelson/gtomscs.py", line 46, in submit
  File "build/bdist.linux-x86_64/egg/nelson/abstract.py", line 32, in submit
  File "build/bdist.linux-x86_64/egg/nelson/abstract.py", line 93, in submit
  File "build/bdist.linux-x86_64/egg/nelson/abstract.py", line 149, in mkzip
ValueError: Submitted files must in subdirectories of /usr/local/bin.
```

Updating line 93 of abstract.py to use "" (empty string) or os.getcwd() fixes the issue. The empty string should be preferred or else the resulting zip file will save the files in a folder when the nelson package is used as an imported script.

**Comment by cgearhart** [comment]
Resolved by commit #a63e67c
